### ISSUE TITLE
Add support for files that have both Tex1 and Tex2 image sbfres and files that have only Tex2

### ISSUE THREAD

**Issue by JakoNintenCraft** [Makiah/BotW-SBFRES-to-FBX#1]
There are certain models in _The Legend of Zelda: Breath of the Wild_ that use more than one texture archive in the form of Tex1 and Tex2.  There are also other models in said game that use just the Tex2 archive strangely enough. So if this project is still being developed for, can this functionality please be added? It would be very helpful as extracting the models from this game is time-consuming as it is. If you need samples to work with, I can provide a few models if necessary.

Thanks for any efforts in advance.
Jako

**Comment by Makiah** [comment]
Interesting, I was under the apparently mistaken impression that Tex2 archives only provided a lower resolution mipmap for the models, and that every model had a Tex1 associated with it.  That said, I haven't searched very thoroughly for exceptions, so what you're saying could well be true.  

If so, I'll definitely try to add that functionality (I've been meaning to update the 3DSMax script for some time now anyway), but I can't guarantee it'll work out considering that I haven't yet seen a tutorial for doing Tex2 extraction (this could change with a bit of research), and this repo is primarily meant to automate those tutorials.  

All the best!
Makiah

**Comment by JakoNintenCraft** [comment]
Every model (minus 1) in the _content/Model_ folder of BOTW's hierarchy (as well as some others) has the Tex1+Text2 configuration.  I have linked a ZIP with the Tex1-only, Tex1+2, and Tex2-only BMS scripts as well as the R6 version of the BFRES importer script. [BFRES.zip](https://github.com/Makiah/BotW-SBFRES-to-FBX/files/1464018/BFRES.zip)  Can't wait for a new version!  Got a big porting project that needs this and this will be a big help!

**Comment by Makiah** [comment]
Oh, interesting!  In retrospect I think I remember seeing this, but for some reason RTB's QuickBMS script didn't work with that script selected (maybe he's updated it recently).  I think that it'd be an easy fix, but I probably won't get to it until later this week at min, so feel free to clone it and maybe try changing that script parameter in the meantime.

**Comment by JakoNintenCraft** [comment]
OK man, so excited!

**Comment by Makiah** [comment]
@JakoNintenCraft finally got the chance to work on this again, but Tex2 files still aren't supported in the MAXscript that I'm using (I didn't develop it), and I doubt they will be as Tex2 typically just contains mipmaps.  I'd suggest you look into https://github.com/KillzXGaming/Smash-Forge if you still want this functionality, I think that KillzXGaming is currently working on that but it's still a WiP last I tested.
