### ISSUE TITLE
Script Makes Duplicate FBX's

### ISSUE THREAD

**Issue by Thisdidnotwork** [Makiah/BotW-SBFRES-to-FBX#6]
Script works well for what I need, but there seems to be a flaw right now where if the Bfres file creates multiple fbx files they will all simply be duplicates of the first instead of what they are supposed to be.

For example, when I open up the armor files in a folder, they all are just the head armor. 

I can simply use the import script manually, but I don't know what the script does to the file to prep it for fbx.

**Comment by Makiah** [comment]
That's odd... I'll take a look later tomorrow, but that sounds like a bug.

**Comment by Makiah** [comment]
I couldn't replicate this issue but forgot to ask for more info, closing unless you're still having the same issue.
